/* 
 * PDF Data Extraction
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = PDFDataExtraction.WebAPI.Client.Client.SwaggerDateConverter;

namespace PDFDataExtraction.WebAPI.Client.Model
{
    /// <summary>
    /// Word
    /// </summary>
    [DataContract]
        public partial class Word :  IEquatable<Word>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Word" /> class.
        /// </summary>
        /// <param name="bbox">bbox.</param>
        /// <param name="chars">chars.</param>
        /// <param name="line">line.</param>
        public Word(BoundingBox bbox = default(BoundingBox), List<Character> chars = default(List<Character>), Line line = default(Line))
        {
            this.Bbox = bbox;
            this.Chars = chars;
            this.Line = line;
        }
        
        /// <summary>
        /// Gets or Sets Bbox
        /// </summary>
        [DataMember(Name="bbox", EmitDefaultValue=false)]
        public BoundingBox Bbox { get; set; }

        /// <summary>
        /// Gets or Sets Chars
        /// </summary>
        [DataMember(Name="chars", EmitDefaultValue=false)]
        public List<Character> Chars { get; set; }

        /// <summary>
        /// Gets or Sets Line
        /// </summary>
        [DataMember(Name="line", EmitDefaultValue=false)]
        public Line Line { get; set; }

        /// <summary>
        /// Gets or Sets Text
        /// </summary>
        [DataMember(Name="text", EmitDefaultValue=false)]
        public string Text { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Word {\n");
            sb.Append("  Bbox: ").Append(Bbox).Append("\n");
            sb.Append("  Chars: ").Append(Chars).Append("\n");
            sb.Append("  Line: ").Append(Line).Append("\n");
            sb.Append("  Text: ").Append(Text).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Word);
        }

        /// <summary>
        /// Returns true if Word instances are equal
        /// </summary>
        /// <param name="input">Instance of Word to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Word input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Bbox == input.Bbox ||
                    (this.Bbox != null &&
                    this.Bbox.Equals(input.Bbox))
                ) && 
                (
                    this.Chars == input.Chars ||
                    this.Chars != null &&
                    input.Chars != null &&
                    this.Chars.SequenceEqual(input.Chars)
                ) && 
                (
                    this.Line == input.Line ||
                    (this.Line != null &&
                    this.Line.Equals(input.Line))
                ) && 
                (
                    this.Text == input.Text ||
                    (this.Text != null &&
                    this.Text.Equals(input.Text))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Bbox != null)
                    hashCode = hashCode * 59 + this.Bbox.GetHashCode();
                if (this.Chars != null)
                    hashCode = hashCode * 59 + this.Chars.GetHashCode();
                if (this.Line != null)
                    hashCode = hashCode * 59 + this.Line.GetHashCode();
                if (this.Text != null)
                    hashCode = hashCode * 59 + this.Text.GetHashCode();
                return hashCode;
            }
        }
    }
}
