version: "3.9"
services:
  grpc-service:
    build:
       context: .
       dockerfile: Dockerfile.grpcservice
       args:
          BUILD_CONFIGURATION: Debug
    ports:
      - "5001:80"
    env_file: grpc-service.env

