version: "3.9"
services:
  webapi:
    build:
       context: .
       dockerfile: Dockerfile.webapi
       args:
          BUILD_CONFIGURATION: Debug
    ports:
      - "9000:80"
    env_file: webapi.env

