/* 
 * PDF Data Extraction
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using PDFDataExtraction.WebAPI.Client.Client;
using PDFDataExtraction.WebAPI.Client.Model;

namespace PDFDataExtraction.WebAPI.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IPDFTextExtractionApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>PDFTextExtractionResult</returns>
        PDFTextExtractionResult DetailedTextExtraction (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);

        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>ApiResponse of PDFTextExtractionResult</returns>
        ApiResponse<PDFTextExtractionResult> DetailedTextExtractionWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);
        /// <summary>
        /// Extract simple text from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>string</returns>
        string SimpleTextExtraction (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);

        /// <summary>
        /// Extract simple text from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>ApiResponse of string</returns>
        ApiResponse<string> SimpleTextExtractionWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of PDFTextExtractionResult</returns>
        System.Threading.Tasks.Task<PDFTextExtractionResult> DetailedTextExtractionAsync (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);

        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of ApiResponse (PDFTextExtractionResult)</returns>
        System.Threading.Tasks.Task<ApiResponse<PDFTextExtractionResult>> DetailedTextExtractionAsyncWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);
        /// <summary>
        /// Extract simple text from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of string</returns>
        System.Threading.Tasks.Task<string> SimpleTextExtractionAsync (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);

        /// <summary>
        /// Extract simple text from a PDF
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        System.Threading.Tasks.Task<ApiResponse<string>> SimpleTextExtractionAsyncWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class PDFTextExtractionApi : IPDFTextExtractionApi
    {
        private PDFDataExtraction.WebAPI.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFTextExtractionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PDFTextExtractionApi(String basePath)
        {
            this.Configuration = new PDFDataExtraction.WebAPI.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = PDFDataExtraction.WebAPI.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFTextExtractionApi"/> class
        /// </summary>
        /// <returns></returns>
        public PDFTextExtractionApi()
        {
            this.Configuration = PDFDataExtraction.WebAPI.Client.Client.Configuration.Default;

            ExceptionFactory = PDFDataExtraction.WebAPI.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PDFTextExtractionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PDFTextExtractionApi(PDFDataExtraction.WebAPI.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = PDFDataExtraction.WebAPI.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = PDFDataExtraction.WebAPI.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public PDFDataExtraction.WebAPI.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public PDFDataExtraction.WebAPI.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>PDFTextExtractionResult</returns>
        public PDFTextExtractionResult DetailedTextExtraction (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {
             ApiResponse<PDFTextExtractionResult> localVarResponse = DetailedTextExtractionWithHttpInfo(_file, convertPdfToImages, wordLineDiff, whiteSpaceFactor);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>ApiResponse of PDFTextExtractionResult</returns>
        public ApiResponse< PDFTextExtractionResult > DetailedTextExtractionWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {

            var localVarPath = "./api/PDFTextExtraction/detailed";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (convertPdfToImages != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "convertPdfToImages", convertPdfToImages)); // query parameter
            if (wordLineDiff != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "wordLineDiff", wordLineDiff)); // query parameter
            if (whiteSpaceFactor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "whiteSpaceFactor", whiteSpaceFactor)); // query parameter
            if (_file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", _file));

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetailedTextExtraction", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PDFTextExtractionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (PDFTextExtractionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PDFTextExtractionResult)));
        }

        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of PDFTextExtractionResult</returns>
        public async System.Threading.Tasks.Task<PDFTextExtractionResult> DetailedTextExtractionAsync (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {
             ApiResponse<PDFTextExtractionResult> localVarResponse = await DetailedTextExtractionAsyncWithHttpInfo(_file, convertPdfToImages, wordLineDiff, whiteSpaceFactor);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract detailed text, including text position, size and font, from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of ApiResponse (PDFTextExtractionResult)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PDFTextExtractionResult>> DetailedTextExtractionAsyncWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {

            var localVarPath = "./api/PDFTextExtraction/detailed";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (convertPdfToImages != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "convertPdfToImages", convertPdfToImages)); // query parameter
            if (wordLineDiff != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "wordLineDiff", wordLineDiff)); // query parameter
            if (whiteSpaceFactor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "whiteSpaceFactor", whiteSpaceFactor)); // query parameter
            if (_file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", _file));

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("DetailedTextExtraction", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PDFTextExtractionResult>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (PDFTextExtractionResult) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PDFTextExtractionResult)));
        }

        /// <summary>
        /// Extract simple text from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>string</returns>
        public string SimpleTextExtraction (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {
             ApiResponse<string> localVarResponse = SimpleTextExtractionWithHttpInfo(_file, convertPdfToImages, wordLineDiff, whiteSpaceFactor);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Extract simple text from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>ApiResponse of string</returns>
        public ApiResponse< string > SimpleTextExtractionWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {

            var localVarPath = "./api/PDFTextExtraction/simple";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (convertPdfToImages != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "convertPdfToImages", convertPdfToImages)); // query parameter
            if (wordLineDiff != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "wordLineDiff", wordLineDiff)); // query parameter
            if (whiteSpaceFactor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "whiteSpaceFactor", whiteSpaceFactor)); // query parameter
            if (_file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", _file));

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SimpleTextExtraction", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Extract simple text from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of string</returns>
        public async System.Threading.Tasks.Task<string> SimpleTextExtractionAsync (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {
             ApiResponse<string> localVarResponse = await SimpleTextExtractionAsyncWithHttpInfo(_file, convertPdfToImages, wordLineDiff, whiteSpaceFactor);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Extract simple text from a PDF 
        /// </summary>
        /// <exception cref="PDFDataExtraction.WebAPI.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="_file"> (optional)</param>
        /// <param name="convertPdfToImages">Set this to &#x60;true&#x60; if the PDF should be converted to PNGs and included in the returned result. Default is &#x60;false&#x60; (optional)</param>
        /// <param name="wordLineDiff">The allowed difference in Y coordinates for words in the same line as a factor of the average character height.  The default value is 0.05 (optional)</param>
        /// <param name="whiteSpaceFactor">How wide the spacing between characters can be before the spacing is considered to be a whitespace, as a factor of the median character width.  The default value is 0.2 (optional)</param>
        /// <returns>Task of ApiResponse (string)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<string>> SimpleTextExtractionAsyncWithHttpInfo (System.IO.Stream _file = null, bool? convertPdfToImages = null, double? wordLineDiff = null, double? whiteSpaceFactor = null)
        {

            var localVarPath = "./api/PDFTextExtraction/simple";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (convertPdfToImages != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "convertPdfToImages", convertPdfToImages)); // query parameter
            if (wordLineDiff != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "wordLineDiff", wordLineDiff)); // query parameter
            if (whiteSpaceFactor != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "whiteSpaceFactor", whiteSpaceFactor)); // query parameter
            if (_file != null) localVarFileParams.Add("file", this.Configuration.ApiClient.ParameterToFile("file", _file));

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SimpleTextExtraction", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (string) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

    }
}
