//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.1.12.0 (Newtonsoft.Json v12.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------

namespace MyNamespace
{
    #pragma warning disable // Disable all warnings

    
}